### ISSUE TITLE
problem with hosting

### ISSUE THREAD

**Issue by rajgoesout** [pengoox/Repo_for_begginers#5]
I guess it is not possible to host a Django site on Github pages. Github pages is for static sites, whereas Django requires Python to generate pages dynamically. You could host it on [https://www.pythonanywhere.com](url)

**Comment by amaanabbasi** [comment]
You are right, Github can only host static pages.

**Comment by rajgoesout** [comment]
check out my blog app ;) 
https://github.com/rajdeepbharati/my-first-blog
