### ISSUE TITLE
More information on django and pip

### ISSUE THREAD

**Issue by neilchauhan2** [pengoox/Repo_for_begginers#6]
Please include more information about pip package manager, as there would be many people who are new to web development and are unaware of package managers. Include a separate doc on pip package manager and how to install that, along with the basic commands to install a package and perform various tasks like - exporting, importing and various other stuffs. As the sole purpose of this project is to help people who are new to Web Development and Open Source, so, in that case this is going to turn out to be real useful.

**Comment by amaanabbasi** [comment]
I have done it already, check docs. 
Should i add more information?

**Comment by neilchauhan2** [comment]
What you have written is about, how to install django using pip. I am asking you to create a separate doc on pip manager with all the basic commands in it. So, people find it easier to use pip.

**Comment by amaanabbasi** [comment]
Done

**Comment by neilchauhan2** [comment]
Now the docs are looking nice and more informative. 👍

**Comment by amaanabbasi** [comment]
We need more documentation
